#!/bin/bash

# Executar como «sudo»
# Ejecutar como «sudo»
# Run with «sudo»

cp minino-desktop-freeze /usr/local/bin/
#chmod +x /usr/local/bin/minino-desktop-freeze
cp minino-desktop-freeze.desktop /usr/local/share/applications/minino/
